### ISSUE TITLE
Can't compile on Mac OS 10.12

### ISSUE THREAD

**Issue by vivek1729** [jpmens/mosquitto-auth-plug#177]
Have built mosquitto from source successfully and want to use HTTP authentication for clients.

When I do `make` , I get the following error.

> Selected backends:          HTTP
Using mosquitto source dir:
OpenSSL install dir:        /usr

If you changed the backend selection, you might need to 'make clean' first

CFLAGS:  -I/src/ -I/lib/ -fPIC -Wall -Werror  -DBE_HTTP  -I/src -DDEBUG=1 -I/usr/include
LDFLAGS:  -L/lib/
LDADD:    -lcurl -L/usr/lib -lcrypto -lmosquitto

cc -I/src/ -I/lib/ -fPIC -Wall -Werror  -DBE_HTTP  -I/src -DDEBUG=1 -I/usr/include   -c -o auth-plug.o auth-plug.c
auth-plug.c:33:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make: *** [auth-plug.o] Error 1

I have `openssl` installed which I can confirm as I did `which openssl` , it output `/usr/bin/openssl`.

While the `openssl` issue seems to be resolved. I am now getting this error 

		lib -lcrypto -lmosquitto
		ld: warning: directory not found for option '-L/lib/'
		Undefined symbols for architecture x86_64:
		  "_PKCS5_PBKDF2_HMAC", referenced from:
		      _pbkdf2_check in pbkdf2-check.o
		ld: symbol(s) not found for architecture x86_64
		clang: error: linker command failed with exit code 1 (use -v to see invocation)
		make: *** [auth-plug.so] Error 1

How do I fix these?

**Comment by vivek1729** [comment]
Fixed this issue by linking homebrew openssl by doing:

`ln -s /usr/local/Cellar/openssl/1.0.2h_1/include/openssl/ /usr/local/include/openssl`
