### ISSUE TITLE
0.0.9 will not build against Openssl 1.0.2

### ISSUE THREAD

**Issue by brandond** [jpmens/mosquitto-auth-plug#183]
It appears that commit a3575f1355e72469d08b38586d64d16863068fb9 broke compilation against older versions of OpenSSL - in my case 1.0.2j. Fails with:
```
cc -I/usr/src/ -I/usr/lib/ -fPIC -Wall -Werror  -DBE_MYSQL -DBE_HTTP -DBE_JWT  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o cache.o cache.c
cache.c: In function 'sha_hash':
cache.c:48:23: error: implicit declaration of function 'EVP_MD_CTX_new' [-Werror=implicit-function-declaration]
   EVP_MD_CTX *mdctx = EVP_MD_CTX_new();
                       ^
cache.c:48:23: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
cache.c:53:3: error: implicit declaration of function 'EVP_MD_CTX_free' [-Werror=implicit-function-declaration]
   EVP_MD_CTX_free(mdctx);
   ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'cache.o' failed
make: *** [cache.o] Error 1
```

Probably need some OpenSSL version conditionals in there.

**Comment by brandond** [comment]
FWIW, here's how Mosquitto handled OpenSSL 1.1.0: https://github.com/eclipse/mosquitto/commit/fff741613eb9dbf462ba7eafe9d9f15f80a9c623

**Comment by leofig-rj** [comment]
See Pull request: Add OpenSSL version conditional around use of EVP_MD_CTX_new/_free #184 https://github.com/jpmens/mosquitto-auth-plug/pull/184/commits/db7e8bac9a6da48b22c3e183a464a9156db0a33d

**Comment by crashev** [comment]
Just stuck on the same problem, after "Fix building against OpenSSL 1.1." in commit a3575f1355e72469d08b38586d64d16863068fb9 ,now it can't be build with OpenSSL 1.0 and as suggested by @leofig-rj there should be conditional there detecting OpenSSL version

**Comment by jpmens** [comment]
Fixed via #184
